version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "12G"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGE_VERSION: "47.3.0"
    volumes:
      - ./data:/data
    restart: unless-stopped


